# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Copy project files
COPY pyproject.toml ./
COPY src ./src

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir 'mcp[cli]>=1.6.0' httpx>=0.28.1 openai>=1.70.0 beautifulsoup4 requests

# Expose a volume for logs if necessary
VOLUME ["/app/logs"]

# Command to run the MCP server using stdio transport
CMD ["python", "src/main.py"]
